- name: Install Password Manager (Dashlane)
  homebrew_cask: name=dashlane state=present

- name: GPG Tools
  homebrew_cask: name=gpgtools state=present

- name: Thunderdbird
  homebrew_cask: name=thunderbird state=present