- name: Install iTerm
  homebrew_cask: name=iterm2 state=present

- name: Install Sublime
  homebrew_cask: name=sublime-text state=present

- name: Setup terminal command to open Sublime
  file: src="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" dest=/usr/local/bin/sublime state=link